### ISSUE TITLE
FSEventStreamStart failed (Parse error on line 3 of app/templates/components/liquid-bind.hbs)

### ISSUE THREAD

**Issue by clov3rly** [ef4/liquid-fire#269]
```
▶ ember serve --proxy http://localhost:3000
version: 0.2.3
The package `ember-data` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-data`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
Proxying to http://localhost:3000
Livereload server on port 35729
Serving on http://localhost:4200/
FSEventStreamStart failed
Error: FSEventStreamStart failed
    at null.<anonymous> (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
    at emitOne (events.js:75:13)
    at emit (events.js:150:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Readable.push (_stream_readable.js:109:10)
    at Transform.push (_stream_transform.js:128:32)
    at JSONStream._transform (/Users/clov3r/Projects/JoyFarm/app/node_modules/ember-cli/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:295:12)
File: app/templates/components/liquid-bind.hbs
Parse error on line 3:
...Class=innerClass as |version| ~}}    {{
-----------------------^
Expecting 'EQUALS', got 'INVALID'
Error: Parse error on line 3:
...Class=innerClass as |version| ~}}    {{
-----------------------^
Expecting 'EQUALS', got 'INVALID'
    at Object.parseError (/Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:107:11)
    at Object.parse (/Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:159:22)
    at HandlebarsEnvironment.parse (/Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:12:17)
    at Object.EmberHandlebars.precompile (/Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/ember-template-compiler/vendor/ember-template-compiler.js:276:24)
    at TemplateCompiler.processString (/Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/index.js:23:24)
    at TemplateCompiler.Filter.processFile (/Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/index.js:139:31)
    at /Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/index.js:85:21
    at lib$rsvp$$internal$$tryCatch (/Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/clov3r/Projects/JoyFarm/app/node_modules/broccoli-ember-hbs-template-compiler/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1095:13
```

Not sure what I'm doing wrong, but after installing liquid-fire, the cli server breaks.

Let me know if I can provide more debugging information, I have no idea what's going on :P

**Comment by clov3rly** [comment]
I needed to update HTMLbars. Not a problem with liquid-fire. Sorry about that :P
