### ISSUE TITLE
how to animate transitions using the component helper

### ISSUE THREAD

**Issue by mgenev** [ef4/liquid-fire#274]
I'm not seeing an obvious way from the docs, is it supported to watch for the component helper's value changing and animate the transition between the new and old?

**Comment by ef4** [comment]
Try

```js
{{#liquid-with componentName as |c|}}
{{component c}}
{{/liquid-with}}
```

**Comment by mgenev** [comment]
Thanks, that seems to to put me on the right track, but I can't seem to control which transition it does, because when I add a class or use like your examples, the build breaks:
```
  {{#liquid-with type as |t|  class="moo"}}
       {{component t status=status}}
  {{/liquid-with}}
```

I get:
```
File: client/pods/components/wizard-form/template.hbs
Parse error on line 11:
...id-with type as |t| class="blah"}}
-----------------------^
Expecting 'CLOSE', got 'ID'
Error: Parse error on line 11:
...id-with type as |t| class="blah"}}
-----------------------^
Expecting 'CLOSE', got 'ID'
    at Object.parseError (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:2713:15)
    at Object.parse (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:2765:26)
    at parse (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:2461:34)
    at preprocess (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:3746:53)
    at compileSpec (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:703:17)
    at TemplateCompiler.exports.default [as precompile] (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:637:12)
    at TemplateCompiler.processString (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-htmlbars/index.js:50:59)
    at TemplateCompiler.Filter.processFile (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:139:31)
    at /Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:85:21
    at lib$rsvp$$internal$$tryCatch (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)
file changed pods/components/wizard-form/template.hbs
```

**Comment by ef4** [comment]
That's not correct handlebars syntax. The block param must come at the end.

**Comment by mgenev** [comment]
I tried that as well, but this:

```
{{#liquid-with class="moo" type as |t|}}

```
gives me 
```
File: client/pods/components/wizard-form/template.hbs
Parse error on line 11:
...th class="moo" type as |t| }}
-----------------------^
Expecting 'EQUALS', got 'OPEN_BLOCK_PARAMS'
Error: Parse error on line 11:
...th class="moo" type as |t| }}
-----------------------^
Expecting 'EQUALS', got 'OPEN_BLOCK_PARAMS'
    at Object.parseError (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:2713:15)
    at Object.parse (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:2765:26)
    at parse (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:2461:34)
    at preprocess (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:3746:53)
    at compileSpec (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:703:17)
    at TemplateCompiler.exports.default [as precompile] (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:637:12)
    at TemplateCompiler.processString (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-htmlbars/index.js:50:59)
    at TemplateCompiler.Filter.processFile (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:139:31)
    at /Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/index.js:85:21
    at lib$rsvp$$internal$$tryCatch (/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-htmlbars/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:489:16)```

**Comment by ef4** [comment]
```handlebars
{{#liquid-with type class="moo" as |t|}}
```

I think it's a bit awkward, but that's the syntax htmlbars gives us.

**Comment by mgenev** [comment]
Awesome that worked as intended! Thank you. Yes, the syntax was hard to find intuitively, I wouldn't have thought to separate the 2 entities i'm aliasing, but another attribute...

**Comment by mgenev** [comment]
I would suggest documenting this, or I could PR it, if you accept those for the docs.
