### ISSUE TITLE
after upgrading to glimmer (canary) liquid fire breaks

### ISSUE THREAD

**Issue by mgenev** [ef4/liquid-fire#276]
I get these errors on my templates:
```
File: client/pods/components/album-picker/template.hbs
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at TransformLiquidWithAsToHash.TransformWithAsToHash_validate [as validate] (/Users/martin.genev/Projects/how-to/client/node_modules/liquid-fire/ext/plugins/transform-liquid-with-as-to-hash.js:45:15)
    at /Users/martin.genev/Projects/how-to/client/node_modules/liquid-fire/ext/plugins/transform-liquid-with-as-to-hash.js:28:23
    at Walker.visit (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:15274:7)
    at visitors.Program (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:15284:16)
    at Walker.children (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:15307:7)
    at Walker.visit (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:15275:12)
    at TransformLiquidWithAsToHash.TransformWithAsToHash_transform [as transform] (/Users/martin.genev/Projects/how-to/client/node_modules/liquid-fire/ext/plugins/transform-liquid-with-as-to-hash.js:27:10)
    at Object.preprocess (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:14877:27)
    at compileSpec (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:10450:22)
    at TemplateCompiler.exports.default [as precompile] (/Users/martin.genev/Projects/how-to/client/bower_components/ember/ember-template-compiler.js:10377:12)
```

**Comment by alexBaizeau** [comment]
Same here, in a pod as well

**Comment by ef4** [comment]
We are not glimmer compatible yet. That particular error is fixed on master
but there is still more to do.

**Comment by davewasmer** [comment]
It would seem that 0.20 is compatible now? Might be able to close this one out.

https://github.com/ef4/liquid-fire#ember-compatibility-table

**Comment by ef4** [comment]
Yes, people should test glimmer with liquid-fire 0.20.0.
