### ISSUE TITLE
liquid-outlet breaks in Ember 1.13.0-beta.1

### ISSUE THREAD

**Issue by Eptis** [ef4/liquid-fire#286]
When using liquid-outlets in 1.13.0-beta.1 I get  `Cannot read property 'path' of undefined`

This is my error log:
```
TypeError: Cannot read property 'path' of undefined
    at TransformLiquidWithAsToHash.TransformWithAsToHash_validate [as validate] (/Users/dennis/Development/Wakoopa/rosalina/node_modules/liquid-fire/ext/plugins/transform-liquid-with-as-to-hash.js:45:15)
    at /Users/dennis/Development/Wakoopa/rosalina/node_modules/liquid-fire/ext/plugins/transform-liquid-with-as-to-hash.js:28:23
    at Walker.visit (/Users/dennis/Development/Wakoopa/rosalina/bower_components/ember/ember-template-compiler.js:15437:7)
    at visitors.ElementNode (/Users/dennis/Development/Wakoopa/rosalina/bower_components/ember/ember-template-compiler.js:15453:16)
    at Walker.children (/Users/dennis/Development/Wakoopa/rosalina/bower_components/ember/ember-template-compiler.js:15470:7)
    at Walker.visit (/Users/dennis/Development/Wakoopa/rosalina/bower_components/ember/ember-template-compiler.js:15438:12)
    at visitors.ElementNode (/Users/dennis/Development/Wakoopa/rosalina/bower_components/ember/ember-template-compiler.js:15453:16)
    at Walker.children (/Users/dennis/Development/Wakoopa/rosalina/bower_components/ember/ember-template-compiler.js:15470:7)
    at Walker.visit (/Users/dennis/Development/Wakoopa/rosalina/bower_components/ember/ember-template-compiler.js:15438:12)
    at visitors.Program (/Users/dennis/Development/Wakoopa/rosalina/bower_components/ember/ember-template-compiler.js:15447:16)
```

**Comment by ef4** [comment]
You need a newer liquid-fire version. See [the compatibility table](https://github.com/ef4/liquid-fire#ember-compatibility-table).

**Comment by Eptis** [comment]
Ah thanks, I missed that. Thought that 0.19 was the latest.



—
Met vriendelijke groet / Kind regards,


Dennis Tel
